import * as path from 'path';
import type { SynthesisResult, SynthesisTask } from '../llm/types';
import { writeText, ensureDir } from '../utils';

const TASK_FILENAMES: Record<SynthesisTask, string> = {
  summarize: 'llm-summary.md',
  risks: 'llm-risks.md',
  refactor: 'llm-refactor.md',
  onboard: 'llm-onboard.md'
};

const TASK_TITLES: Record<SynthesisTask, string> = {
  summarize: 'LLM Executive Summary',
  risks: 'LLM Deep Risk Analysis',
  refactor: 'LLM Refactor Plan',
  onboard: 'LLM Onboarding Guide'
};

export function exportLLMResults(results: SynthesisResult[], outputDir: string): void {
  const llmDir = path.join(outputDir, 'llm');
  ensureDir(llmDir);

  for (const result of results) {
    const filename = TASK_FILENAMES[result.task];
    const title = TASK_TITLES[result.task];
    const header = [
      `# ${title}`,
      '',
      `> Generated by **${result.provider}** / \`${result.model}\` on ${result.generatedAt}`,
      '',
      '---',
      ''
    ].join('\n');

    writeText(path.join(llmDir, filename), header + result.content + '\n');
  }

  // Write an index file
  if (results.length > 0) {
    const index = [
      '# LLM Synthesis Index',
      '',
      `Provider: **${results[0].provider}** | Model: \`${results[0].model}\``,
      '',
      '| Task | File |',
      '| --- | --- |',
      ...results.map((r) => `| ${TASK_TITLES[r.task]} | [${TASK_FILENAMES[r.task]}](./${TASK_FILENAMES[r.task]}) |`),
      ''
    ].join('\n');
    writeText(path.join(llmDir, 'index.md'), index);
  }
}
